'use client';
import { useState } from 'react';

const COLOR = '#ef4444';

interface Option { key: string; label: string; desc: string; snippet: string; }

const OPTIONS: Option[] = [
  {
    key: 'https',
    label: 'Force HTTPS',
    desc: 'Redirect all HTTP to HTTPS',
    snippet: `RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`,
  },
  {
    key: 'www',
    label: 'Force www',
    desc: 'Redirect non-www to www',
    snippet: `RewriteEngine On
RewriteCond %{HTTP_HOST} !^www\\.
RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`,
  },
  {
    key: 'nowww',
    label: 'Remove www',
    desc: 'Redirect www to non-www',
    snippet: `RewriteEngine On
RewriteCond %{HTTP_HOST} ^www\\.(.*)$ [NC]
RewriteRule ^(.*)$ https://%1%{REQUEST_URI} [L,R=301]`,
  },
  {
    key: 'cache',
    label: 'Browser Caching',
    desc: 'Add cache headers for static assets',
    snippet: `<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType image/jpg "access plus 1 year"
  ExpiresByType image/jpeg "access plus 1 year"
  ExpiresByType image/png "access plus 1 year"
  ExpiresByType image/webp "access plus 1 year"
  ExpiresByType text/css "access plus 1 month"
  ExpiresByType application/javascript "access plus 1 month"
</IfModule>`,
  },
  {
    key: 'gzip',
    label: 'Enable Gzip Compression',
    desc: 'Compress text files for faster delivery',
    snippet: `<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css
  AddOutputFilterByType DEFLATE application/javascript application/json
  AddOutputFilterByType DEFLATE image/svg+xml
</IfModule>`,
  },
  {
    key: 'hotlink',
    label: 'Prevent Hotlinking',
    desc: 'Block other sites from embedding your images',
    snippet: `RewriteEngine On
RewriteCond %{HTTP_REFERER} !^$
RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?yourdomain\\.com [NC]
RewriteRule \\.(jpg|jpeg|png|gif|webp|svg)$ - [F,NC]`,
  },
  {
    key: 'directory',
    label: 'Disable Directory Listing',
    desc: 'Prevent browsing of directories',
    snippet: 'Options -Indexes',
  },
  {
    key: 'dotfiles',
    label: 'Protect .env Files',
    desc: 'Block access to sensitive config files',
    snippet: `<Files ~ "^\\.">
  Order allow,deny
  Deny from all
</Files>`,
  },
  {
    key: 'trailing',
    label: 'Remove Trailing Slash',
    desc: 'Canonical URL: remove trailing slash',
    snippet: `RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)/$ /$1 [L,R=301]`,
  },
  {
    key: 'php',
    label: 'PHP Single Entry Point',
    desc: 'Route all requests through index.php (Laravel / Symfony)',
    snippet: `RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]`,
  },
];

export default function HtaccessGenerator() {
  const [selected, setSelected] = useState<Set<string>>(new Set(['https', 'directory']));
  const [copied, setCopied] = useState(false);

  function toggle(key: string) {
    setSelected((s) => { const n = new Set(s); n.has(key) ? n.delete(key) : n.add(key); return n; });
  }

  const output = '# Generated by Xgenious .htaccess Generator\n\n' +
    OPTIONS.filter((o) => selected.has(o.key))
      .map((o) => `# ${o.label}\n${o.snippet}`)
      .join('\n\n');

  function copy() {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function download() {
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = '.htaccess'; a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="flex flex-col gap-5">
      <div className="grid sm:grid-cols-2 gap-3">
        {OPTIONS.map((o) => (
          <label key={o.key} className="flex items-start gap-3 cursor-pointer p-3 rounded-xl border border-[#E5E7EC] hover:border-[#ef4444] transition-colors">
            <input type="checkbox" checked={selected.has(o.key)} onChange={() => toggle(o.key)}
              className="w-4 h-4 accent-[#ef4444] mt-0.5 flex-shrink-0" />
            <div>
              <div className="text-[13px] font-semibold text-[#0F1112]">{o.label}</div>
              <div className="text-[11px] text-[#9ca3af] mt-0.5">{o.desc}</div>
            </div>
          </label>
        ))}
      </div>

      <div className="flex flex-col gap-2">
        <div className="flex items-center justify-between">
          <label className="text-[13px] font-semibold text-[#0F1112]">Generated .htaccess</label>
          <div className="flex gap-3">
            <button onClick={copy} className="text-[12px] text-[#ef4444] hover:underline">{copied ? 'Copied!' : 'Copy'}</button>
            <button onClick={download} className="text-[12px] text-[#ef4444] hover:underline">Download</button>
          </div>
        </div>
        <pre className="rounded-xl border border-[#E5E7EC] bg-[#F5F6F8] px-5 py-4 text-[12px] font-mono text-[#0F1112] whitespace-pre overflow-x-auto leading-5 max-h-80 overflow-y-auto">
          {output}
        </pre>
      </div>
    </div>
  );
}
