import type { Metadata } from 'next';
import PolicyLayout from '@/components/ui/PolicyLayout';

export const metadata: Metadata = {
  title: 'Privacy Policy — Xgenious',
  description: 'How Xgenious collects, uses, and protects your personal data.',
};

export default function PrivacyPolicyPage() {
  return (
    <PolicyLayout title="Privacy Policy" badge="Legal" lastUpdated="January 16, 2025">
      <h2>1. Introduction</h2>
      <p>
        Welcome to XGENIOUS. XGENIOUS ("us", "we", or "our") operates <a href="https://xgenious.com/">https://xgenious.com/</a> (hereinafter referred to as "Service"). Our Privacy Policy governs your visit to our website and explains how we collect, safeguard and disclose information that results from your use of our Service.
      </p>
      <p>
        We use your data to provide and improve our Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used have the same meanings as in our Terms and Conditions.
      </p>

      <h2>2. Definitions</h2>
      <ul>
        <li><strong>SERVICE</strong> means the https://xgenious.com/ website operated by XGENIOUS.</li>
        <li><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data.</li>
        <li><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself.</li>
        <li><strong>COOKIES</strong> are small files stored on your device (computer or mobile device).</li>
        <li><strong>DATA CONTROLLER</strong> means a natural or legal person who determines the purposes for which and the manner in which any personal data are processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</li>
        <li><strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any natural or legal person who processes the data on behalf of the Data Controller.</li>
        <li><strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal Data.</li>
        <li><strong>THE USER</strong> is the individual using our Service.</li>
      </ul>

      <h2>3. Information Collection and Use</h2>
      <p>
        We collect several different types of information for various purposes to provide and improve our Service to you.
      </p>

      <h2>4. Types of Data Collected</h2>

      <h3>Personal Data</h3>
      <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This may include, but is not limited to:</p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, Country, State, Province, ZIP/Postal code, City</li>
        <li>Cookies and Usage Data</li>
      </ul>
      <p>
        We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
      </p>

      <h3>Usage Data</h3>
      <p>
        We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device. This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
      </p>

      <h3>Tracking Cookies Data</h3>
      <p>
        We use cookies and similar tracking technologies to track the activity on our Service. Cookies are files with a small amount of data which may include an anonymous unique identifier. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
      </p>
      <p>Examples of Cookies we use:</p>
      <ul>
        <li><strong>Session Cookies:</strong> We use Session Cookies to operate our Service.</li>
        <li><strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings.</li>
        <li><strong>Security Cookies:</strong> We use Security Cookies for security purposes.</li>
        <li><strong>Advertising Cookies:</strong> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
      </ul>

      <h2>5. Use of Data</h2>
      <p>XGENIOUS uses the collected data for various purposes:</p>
      <ul>
        <li>To provide and maintain our Service</li>
        <li>To notify you about changes to our Service</li>
        <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
        <li>To provide customer support</li>
        <li>To gather analysis or valuable information so that we can improve our Service</li>
        <li>To monitor the usage of our Service</li>
        <li>To detect, prevent and address technical issues</li>
        <li>To fulfil any other purpose for which you provide it</li>
        <li>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us</li>
        <li>To provide you with notices about your account and/or subscription, including expiration and renewal notices</li>
        <li>To provide you with news, special offers and general information about other goods, services and events which we offer</li>
        <li>For any other purpose with your consent</li>
      </ul>

      <h2>6. Retention of Data</h2>
      <p>
        We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
      </p>
      <p>
        We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service.
      </p>

      <h2>7. Transfer of Data</h2>
      <p>
        Your information, including Personal Data, may be transferred to and maintained on computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
      </p>
      <p>
        If you are located outside Dhaka, Bangladesh and choose to provide information to us, please note that we transfer the data, including Personal Data, to Dhaka, Bangladesh and process it there. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
      </p>

      <h2>8. Disclosure of Data</h2>
      <p>We may disclose personal information that we collect, or you provide:</p>
      <ul>
        <li><strong>Disclosure for Law Enforcement:</strong> Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</li>
        <li><strong>Business Transaction:</strong> If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</li>
        <li>To our subsidiaries and affiliates</li>
        <li>To contractors, service providers, and other third parties we use to support our business</li>
        <li>To fulfill the purpose for which you provide it</li>
        <li>With your consent in any other cases</li>
        <li>If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others</li>
      </ul>

      <h2>9. Security of Data</h2>
      <p>
        The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
      </p>

      <h2>10. Your Data Protection Rights Under GDPR</h2>
      <p>
        If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights covered by GDPR. We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
      </p>
      <p>In certain circumstances, you have the following data protection rights:</p>
      <ul>
        <li>The right to access, update or delete the information we have on you</li>
        <li>The right of rectification — to have your information rectified if inaccurate or incomplete</li>
        <li>The right to object to our processing of your Personal Data</li>
        <li>The right of restriction — to request that we restrict the processing of your personal information</li>
        <li>The right to data portability</li>
        <li>The right to withdraw consent at any time</li>
      </ul>
      <p>
        If you wish to be informed what Personal Data we hold about you or want it to be removed from our systems, please email us at <a href="mailto:contact@xgenious.com">contact@xgenious.com</a>.
      </p>

      <h2>11. Your Data Protection Rights under CalOPPA</h2>
      <p>
        CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. According to CalOPPA we agree to the following:
      </p>
      <ul>
        <li>Users can visit our site anonymously</li>
        <li>Our Privacy Policy link includes the word "Privacy" and can easily be found on the home page</li>
        <li>Users will be notified of any privacy policy changes on our Privacy Policy Page</li>
        <li>Users are able to change their personal information by emailing us at <a href="mailto:contact@xgenious.com">contact@xgenious.com</a></li>
      </ul>
      <p>
        We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place.
      </p>

      <h2>12. Your Data Protection Rights under the CCPA</h2>
      <p>
        If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us what personal information we have about you.
      </p>
      <p>
        We don&apos;t sell or rent your personal information to any third parties for any purpose. To exercise your California data protection rights, please send your request(s) by email: <a href="mailto:contact@xgenious.com">contact@xgenious.com</a>.
      </p>

      <h2>13. Service Providers</h2>
      <p>
        We may employ third party companies and individuals to facilitate our Service, provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
      </p>

      <h2>14. Analytics</h2>
      <p>
        We may use third-party Service Providers to monitor and analyze the use of our Service.
      </p>

      <h2>15. Payments</h2>
      <p>
        We may provide paid products and/or services within our Service. In that case, we use third-party services for payment processing. We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy.
      </p>

      <h2>16. Links to Other Sites</h2>
      <p>
        Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party&apos;s site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
      </p>

      <h2>17. Children&apos;s Privacy</h2>
      <p>
        Our Services are not intended for use by children under the age of 18. We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us.
      </p>

      <h2>18. Changes to This Privacy Policy</h2>
      <p>
        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
      </p>

      <h2>19. Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, please contact us by email: <a href="mailto:contact@xgenious.com">contact@xgenious.com</a>
      </p>
    </PolicyLayout>
  );
}
