import type { MetadataRoute } from 'next';

const BASE_URL = 'https://xgenious.com';

export default function sitemap(): MetadataRoute.Sitemap {
  const staticPages = [
    { url: BASE_URL, lastModified: '2026-07-19', priority: 1.0, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/about`, lastModified: '2026-05-17', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/contact`, lastModified: '2026-05-17', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/book-a-call`, lastModified: '2026-05-21', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/web-app-development-company`, lastModified: '2026-05-17', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/mobile-app-development`, lastModified: '2026-05-17', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/custom-saas-development-company`, lastModified: '2026-05-17', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agent-development-services`, lastModified: '2026-05-17', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-ecommerce`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-education`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-finance`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-healthcare`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-hr-recruiting`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-logistics`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-real-estate`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-saas`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/saas-mvp-development`, lastModified: '2026-05-20', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/ai-support-saas-platform`, lastModified: '2026-05-20', priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/beauty-room-booking-app`, lastModified: '2026-05-20', priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/car-service-marketplace`, lastModified: '2026-05-20', priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/classified-ads-platform`, lastModified: '2026-05-20', priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/crowdfunding-platform`, lastModified: '2026-05-20', priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/ecommerce-platform-with-courier`, lastModified: '2026-05-20', priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/freelancer-marketplace-platform`, lastModified: '2026-05-20', priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/multi-tenant-ecommerce-saas`, lastModified: '2026-05-20', priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/on-demand-home-service-app`, lastModified: '2026-05-20', priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/privacy-policy`, lastModified: '2026-05-17', priority: 0.3, changeFrequency: 'yearly' as const },
    { url: `${BASE_URL}/refund-policy`, lastModified: '2026-05-17', priority: 0.3, changeFrequency: 'yearly' as const },
    { url: `${BASE_URL}/support-policy`, lastModified: '2026-05-17', priority: 0.3, changeFrequency: 'yearly' as const },
    { url: `${BASE_URL}/terms-of-service`, lastModified: '2026-05-17', priority: 0.3, changeFrequency: 'yearly' as const },
    { url: `${BASE_URL}/products/nazmart-multi-tenancy-ecommerce-platform`, lastModified: '2026-05-28', priority: 0.9, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/products/xilancer-freelancer-marketplace-script`, lastModified: '2026-05-28', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/fundorex-crowdfunding-platform`, lastModified: '2026-05-30', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/helpnest-ai-chatbot-support-script`, lastModified: '2026-05-31', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/prohandy-on-demand-home-service-marketplace`, lastModified: '2026-06-04', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/gocar-on-demand-car-service-marketplace`, lastModified: '2026-06-09', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/qixer-on-demand-service-marketplace`, lastModified: '2026-06-09', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/botmerze-ai-chatbot-saas-ecommerce`, lastModified: '2026-06-15', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/multisaas-website-builder-saas`, lastModified: '2026-06-16', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/grenmart-organic-grocery-ecommerce`, lastModified: '2026-06-23', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/nexelit-multipurpose-website-business-management-system-cms`, lastModified: '2026-06-25', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/listocean-classified-ads-listing-platform`, lastModified: '2026-06-25', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/safecart-multi-vendor-laravel-ecommerce-platform`, lastModified: '2026-06-27', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/influstar-influencer-hiring-marketplace-platform`, lastModified: '2026-06-29', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/zaika-ecommerce-shopping-laravel-platform`, lastModified: '2026-06-29', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-software`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-software/genius-school-management`, lastModified: '2026-05-20', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-software/genius-crm`, lastModified: '2026-05-20', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-software/genius-hrm`, lastModified: '2026-05-20', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-software/genius-support`, lastModified: '2026-06-04', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-software/genius-campaign`, lastModified: '2026-07-19', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-software/genius-debug`, lastModified: '2026-07-19', priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-tools`, lastModified: '2026-05-20', priority: 0.9, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/json-formatter`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/password-generator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/base64-encoder-decoder`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/jwt-decoder`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/regex-tester`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/cron-expression-builder`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/env-file-generator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/sql-formatter`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/color-contrast-checker`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/htaccess-generator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/ai-token-cost-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/payroll-breakdown-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/employee-cost-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/leave-accrual-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/salary-hike-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/overtime-pay-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/gpa-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/attendance-percentage-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/exam-grade-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/school-fee-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/mvp-cost-estimator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/churn-rate-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/customer-ltv-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/mrr-growth-simulator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/build-vs-buy-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/sales-pipeline-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/cold-email-roi-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/meeting-cost-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/freelance-rate-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/saas-pricing-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/saas-runway-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/sales-commission-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/cac-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/lead-response-time-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/invoice-generator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/business-name-generator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/time-zone-meeting-planner`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/project-timeline-estimator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/sprint-velocity-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/custom-software-roi-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/equity-dilution-calculator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/job-description-generator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/interview-question-generator`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/tech-stack-recommender`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/png-to-webp`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/jpg-to-webp`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/png-to-avif`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/jpg-to-avif`, lastModified: '2026-05-20', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/saas-calculators`, lastModified: '2026-07-09', priority: 0.9, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/break-even-calculator`, lastModified: '2026-07-09', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/saas-valuation-calculator`, lastModified: '2026-07-09', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/nrr-calculator`, lastModified: '2026-07-09', priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/payback-period-calculator`, lastModified: '2026-07-09', priority: 0.8, changeFrequency: 'weekly' as const },
  ];

  return staticPages.map((page) => ({
    url: page.url,
    lastModified: page.lastModified,
    changeFrequency: page.changeFrequency,
    priority: page.priority,
  }));
}
