import type { MetadataRoute } from 'next';

const BASE_URL = 'https://xgenious.com';

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const staticPages = [
    { url: BASE_URL, priority: 1.0, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/about`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/contact`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/book-a-call`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/web-app-development-company`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/mobile-app-development`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/custom-saas-development-company`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agent-development-services`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-ecommerce`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-education`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-finance`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-healthcare`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-hr-recruiting`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-logistics`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-real-estate`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/ai-agents-for-saas`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/saas-mvp-development`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/ai-support-saas-platform`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/beauty-room-booking-app`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/car-service-marketplace`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/classified-ads-platform`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/crowdfunding-platform`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/ecommerce-platform-with-courier`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/freelancer-marketplace-platform`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/multi-tenant-ecommerce-saas`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/case-studies/on-demand-home-service-app`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/privacy-policy`, priority: 0.3, changeFrequency: 'yearly' as const },
    { url: `${BASE_URL}/refund-policy`, priority: 0.3, changeFrequency: 'yearly' as const },
    { url: `${BASE_URL}/support-policy`, priority: 0.3, changeFrequency: 'yearly' as const },
    { url: `${BASE_URL}/terms-of-service`, priority: 0.3, changeFrequency: 'yearly' as const },
    { url: `${BASE_URL}/products/nazmart-multi-tenancy-ecommerce-platform`, priority: 0.9, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/products/xilancer-freelancer-marketplace-script`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/fundorex-crowdfunding-platform`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/helpnest-ai-chatbot-support-script`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/prohandy-on-demand-home-service-marketplace`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/gocar-on-demand-car-service-marketplace`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/qixer-on-demand-service-marketplace`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/botmerze-ai-chatbot-saas-ecommerce`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/multisaas-website-builder-saas`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/grenmart-organic-grocery-ecommerce`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/nexelit-multipurpose-website-business-management-system-cms`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/listocean-classified-ads-listing-platform`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/safecart-multi-vendor-laravel-ecommerce-platform`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/products/influstar-influencer-hiring-marketplace-platform`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-software`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-software/genius-school-management`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-software/genius-crm`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-software/genius-hrm`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-software/genius-support`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${BASE_URL}/free-tools`, priority: 0.9, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/json-formatter`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/password-generator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/base64-encoder-decoder`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/jwt-decoder`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/regex-tester`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/cron-expression-builder`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/env-file-generator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/sql-formatter`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/color-contrast-checker`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/htaccess-generator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/ai-token-cost-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/payroll-breakdown-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/employee-cost-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/leave-accrual-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/salary-hike-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/overtime-pay-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/gpa-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/attendance-percentage-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/exam-grade-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/school-fee-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/mvp-cost-estimator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/churn-rate-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/customer-ltv-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/mrr-growth-simulator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/build-vs-buy-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/sales-pipeline-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/cold-email-roi-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/meeting-cost-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/freelance-rate-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/saas-pricing-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/saas-runway-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/sales-commission-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/cac-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/lead-response-time-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/invoice-generator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/business-name-generator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/time-zone-meeting-planner`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/project-timeline-estimator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/sprint-velocity-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/custom-software-roi-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/equity-dilution-calculator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/job-description-generator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/interview-question-generator`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/tech-stack-recommender`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/png-to-webp`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/jpg-to-webp`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/png-to-avif`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${BASE_URL}/free-tools/jpg-to-avif`, priority: 0.8, changeFrequency: 'weekly' as const },
  ];

  return staticPages.map((page) => ({
    url: page.url,
    lastModified: now,
    changeFrequency: page.changeFrequency,
    priority: page.priority,
  }));
}
