export interface CheckoutAddon {
  path: string;
  label: string;
  description: string;
  price: number;
  originalPrice: number;
  bestValue?: boolean;
  sidebarUpsell?: boolean;
  disables?: string[];
  includes?: string[];
  excludes?: string[];
}

export interface CheckoutProduct {
  path: string;
  name: string;
  tagline: string;
  price: number;
  originalPrice: number;
  badge?: string;
  features: string[];
  addons: CheckoutAddon[];
}

const PRODUCTS: Record<string, CheckoutProduct> = {
  'xilancer-bundle-pack': {
    path: 'xilancer-bundle-pack',
    name: 'Xilancer — Everything Bundle',
    tagline: 'Web Platform + 2 Mobile Apps + All Premium Plugins',
    price: 99,
    originalPrice: 282,
    badge: 'Commercial Use',
    features: [
      'Xilancer Web Platform',
      'Admin Panel & Analytics',
      'Escrow Payment System',
      'Real-Time Chat',
      'Freelancer Mobile App (Flutter)',
      'Client Mobile App (Flutter)',
      'Freelancer Level Plugin',
      'Promotional Ads Plugin',
      'Security Plugin',
      'Cloud Storage Plugin',
      'Hourly Hiring Plugin',
      'Community Plugin',
      'Lifetime License + Free Updates',
      '6 Months Support',
    ],
    addons: [
      {
        path: 'xilancer-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 50,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'xilancer-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We deploy Xilancer on your server, configure everything, and hand you the keys.',
        price: 100,
        originalPrice: 299,
        includes: [
          'API connection & configuration',
          'Branding assets & color customization',
          'Translation / multi-language setup',
          'Google Play Store release',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
      {
        path: 'xilancer-install-web-mobile',
        label: 'Full Done-For-You Launch (Web + Both Apps)',
        description: 'Your complete marketplace, live in days. Web platform + both branded mobile apps — fully configured, nothing left for you to figure out.',
        price: 499,
        originalPrice: 1090,
        bestValue: true,
        disables: ['xilancer-install-web'],
        includes: [
          'API connection & configuration',
          'Branding assets & color customization',
          'Translation / multi-language setup',
          'Google Play Store release',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
      {
        path: 'xilancer-appstore-google',
        label: 'Publish Both Apps to Google Play — We Handle It',
        description: 'Your apps, live on Google Play. We sign, submit, and follow up with Google until both apps are approved.',
        price: 398,
        originalPrice: 800,
        includes: [
          'APK signing & release build',
          'Google Play Console submission for both apps',
          'Store listing setup (title, description, screenshots)',
          'App review follow-up until approved',
        ],
        excludes: [
          'Google Play developer account ($25 one-time fee — you must own it)',
          'App icons or screenshots (you provide)',
        ],
      },
      {
        path: 'xilancer-appstore-apple',
        label: 'Publish Both Apps to the App Store — We Handle It',
        description: 'Your apps, live on the App Store. We handle signing, submission, and App Store review until both are approved.',
        price: 398,
        originalPrice: 800,
        includes: [
          'IPA build & code signing',
          'App Store Connect submission for both apps',
          'Store listing setup (title, description, screenshots)',
          'App review follow-up until approved',
        ],
        excludes: [
          'Apple Developer account ($99/yr — you must own it)',
          'App icons or screenshots (you provide)',
        ],
      },
    ],
  },

  'xilancer-exclusive-pack': {
    path: 'xilancer-exclusive-pack',
    name: 'Xilancer — Exclusive License',
    tagline: 'Full source code ownership. Modify anything. No restrictions.',
    price: 299,
    originalPrice: 500,
    badge: 'For Businesses',
    features: [
      'Everything in Everything Bundle',
      'Full Source Code Modification Rights',
      'Remove / Replace Any Branding',
      'No License Key Enforcement',
      'Priority Support — 12 Months',
      'Commercial Use — Unlimited Projects',
      'Lifetime License + Free Updates',
      'Cannot be resold or redistributed as-is',
    ],
    addons: [
      {
        path: 'xilancer-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 50,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'xilancer-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We deploy Xilancer on your server, configure everything, and hand you the keys.',
        price: 100,
        originalPrice: 299,
        includes: [
          'API connection & configuration',
          'Branding assets & color customization',
          'Translation / multi-language setup',
          'Google Play Store release',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
      {
        path: 'xilancer-install-web-mobile',
        label: 'Full Done-For-You Launch (Web + Both Apps)',
        description: 'Your complete marketplace, live in days. Web platform + both branded mobile apps — fully configured, nothing left for you to figure out.',
        price: 499,
        originalPrice: 1090,
        bestValue: true,
        disables: ['xilancer-install-web'],
        includes: [
          'API connection & configuration',
          'Branding assets & color customization',
          'Translation / multi-language setup',
          'Google Play Store release',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
    ],
  },
  'nazmart-bundle-pack': {
    path: 'nazmart-bundle-pack',
    name: 'Nazmart — Everything Bundle',
    tagline: 'Web Platform + All 17 Premium Plugins + Mobile App',
    price: 99,
    originalPrice: 199,
    badge: 'Web + Plugins + Mobile App',
    features: [
      'Nazmart Web Platform',
      'AI Integration Plugin',
      'Abandoned Cart Recovery',
      'Cart Discount Plugin',
      'FOMO Notification',
      'GDPR Data Export',
      'Multi Currency',
      'Point of Sales Plugin',
      'Product Badge',
      'Site Analytics',
      'Shipping Plugin',
      'Affiliate Program',
      'Google Merchant Feed Sync',
      'Loyalty Points',
      'SMS Gateway',
      'WooCommerce Import',
      'Cloud Storage Plugin',
      'Mobile App (Flutter)',
      'Lifetime License + Free Updates',
      '6 Months Support',
    ],
    addons: [
      {
        path: 'nazmart-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'nazmart-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We deploy Nazmart on your server, configure everything, and hand you the keys.',
        price: 149,
        originalPrice: 299,
        includes: [
          'Application installation & configuration on your server',
          'Branding assets & color customization',
          'Payment gateway configuration',
          'Translation / multi-language setup',
        ],
        excludes: [
          'Domain, hosting, VPS or server procurement',
        ],
      },
      {
        path: 'nazmart-install-web-and-mobile',
        label: 'Full Done-For-You Launch (Web + Mobile)',
        description: 'Your complete marketplace, live in days. Web platform + primary mobile app — fully configured, nothing left for you to figure out.',
        price: 449,
        originalPrice: 900,
        bestValue: true,
        disables: ['nazmart-install-web'],
        includes: [
          'Application installation & configuration on your server',
          'Branding assets & color customization',
          'Payment gateway configuration',
          'Translation / multi-language setup',
          'Mobile app build & configuration (1 primary master app)',
        ],
        excludes: [
          'Domain, hosting, VPS or server procurement',
          'Individual tenant app compilation or publishing',
        ],
      },
    ],
  },

  'fundorex-regular': {
    path: 'fundorex-regular',
    name: 'Fundorex — Regular License',
    tagline: 'Self-hosted crowdfunding platform. Web platform only.',
    price: 69,
    originalPrice: 99,
    features: [
      'Fundorex Web Platform',
      'Admin Panel & Analytics',
      'All Platform Features',
      '20+ Payment Gateways',
      'Event Ticketing Module',
      'Donor Wallet System',
      'Volunteer Management',
      'Community Campaigns',
      'Lifetime License + Free Updates',
      '6 Months Support',
    ],
    addons: [
      {
        path: 'fundorex-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'fundorex-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We deploy Fundorex on your server, configure everything, and hand you the keys.',
        price: 99,
        originalPrice: 299,
        includes: [
          'Server setup & configuration',
          'Payment gateway configuration',
          'Branding assets & color customization',
          'Translation / multi-language setup',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
    ],
  },

  'fundorex-bundle-pack': {
    path: 'fundorex-bundle-pack',
    name: 'Fundorex — Everything Bundle',
    tagline: 'Web Platform + Flutter Mobile App — all in one.',
    price: 79,
    originalPrice: 118,
    badge: 'Mobile App Included',
    features: [
      'Fundorex Web Platform',
      'Admin Panel & Analytics',
      'All Platform Features',
      '20+ Payment Gateways',
      'Event Ticketing Module',
      'Donor Wallet System',
      'Volunteer Management',
      'Community Campaigns',
      'Flutter Mobile App (Android + iOS)',
      'Lifetime License + Free Updates',
      '6 Months Support',
    ],
    addons: [
      {
        path: 'fundorex-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'fundorex-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We deploy Fundorex on your server, configure everything, and hand you the keys.',
        price: 99,
        originalPrice: 299,
        includes: [
          'Server setup & configuration',
          'Payment gateway configuration',
          'Branding assets & color customization',
          'Translation / multi-language setup',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
      {
        path: 'fundorex-install-web-mobile',
        label: 'Full Done-For-You Launch (Web + Mobile App)',
        description: 'Your complete crowdfunding platform, live in days. Web + branded mobile app — fully configured, nothing left for you to figure out.',
        price: 399,
        originalPrice: 900,
        bestValue: true,
        disables: ['fundorex-install-web'],
        includes: [
          'Server setup & configuration',
          'Payment gateway configuration',
          'Branding assets & color customization',
          'Translation / multi-language setup',
          'Mobile app build & configuration',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
      {
        path: 'fundorex-appstore-google',
        label: 'Publish Mobile App to Google Play — We Handle It',
        description: 'Your app, live on Google Play. We sign, submit, and follow up with Google until approved.',
        price: 199,
        originalPrice: 399,
        includes: [
          'APK signing & release build',
          'Google Play Console submission',
          'Store listing setup (title, description, screenshots)',
          'App review follow-up until approved',
        ],
        excludes: [
          'Google Play developer account ($25 one-time fee — you must own it)',
          'App icons or screenshots (you provide)',
        ],
      },
      {
        path: 'fundorex-appstore-apple',
        label: 'Publish Mobile App to App Store — We Handle It',
        description: 'Your app, live on the App Store. We handle signing, submission, and App Store review until approved.',
        price: 199,
        originalPrice: 399,
        includes: [
          'IPA build & code signing',
          'App Store Connect submission',
          'Store listing setup (title, description, screenshots)',
          'App review follow-up until approved',
        ],
        excludes: [
          'Apple Developer account ($99/yr — you must own it)',
          'App icons or screenshots (you provide)',
        ],
      },
    ],
  },

  'fundorex-exclusive-pack': {
    path: 'fundorex-exclusive-pack',
    name: 'Fundorex — Extended License',
    tagline: 'Full source code ownership. Modify anything. No restrictions.',
    price: 199,
    originalPrice: 299,
    badge: 'For Businesses',
    features: [
      'Everything in Everything Bundle',
      'Flutter Mobile App (Android + iOS)',
      'Full Source Code Modification Rights',
      'Remove / Replace Any Branding',
      'Commercial Use — Unlimited Projects',
      'Priority Support — 12 Months',
      'Lifetime License + Free Updates',
      'Cannot be resold or redistributed as-is',
    ],
    addons: [
      {
        path: 'fundorex-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We deploy Fundorex on your server, configure everything, and hand you the keys.',
        price: 99,
        originalPrice: 299,
        includes: [
          'Server setup & configuration',
          'Payment gateway configuration',
          'Branding assets & color customization',
          'Translation / multi-language setup',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
      {
        path: 'fundorex-install-web-mobile',
        label: 'Full Done-For-You Launch (Web + Mobile App)',
        description: 'Your complete crowdfunding platform, live in days. Web + branded mobile app — fully configured, nothing left for you to figure out.',
        price: 399,
        originalPrice: 900,
        bestValue: true,
        disables: ['fundorex-install-web'],
        includes: [
          'Server setup & configuration',
          'Payment gateway configuration',
          'Branding assets & color customization',
          'Translation / multi-language setup',
          'Mobile app build & configuration',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
    ],
  },

  'helpnest-regular': {
    path: 'helpnest-regular',
    name: 'Helpnest — Regular License',
    tagline: 'Self-hosted AI chatbot platform. Web platform only.',
    price: 59,
    originalPrice: 89,
    features: [
      'Helpnest Web Platform',
      'Admin Panel & Analytics',
      'AI Chatbot (OpenAI + Claude)',
      'Support Ticketing System',
      'Knowledge Base Builder',
      'Visitor Tracking',
      'Embeddable Chat Widget',
      'Stripe + PayPal Billing',
      'Lifetime License + Updates',
      '6 Months Support',
    ],
    addons: [
      {
        path: 'helpnest-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'helpnest-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We configure your VPS, PostgreSQL with vector extension, OCR, and deploy Helpnest — ready to go.',
        price: 149,
        originalPrice: 299,
        includes: [
          'VPS server setup & configuration',
          'PostgreSQL 14+ with pgvector extension',
          'OCR configuration',
          'AI provider (OpenAI / Claude) connection',
          'Stripe / PayPal payment configuration',
        ],
        excludes: [
          'Domain, hosting, VPS or server cost',
        ],
      },
    ],
  },

  'helpnest-everything-bundle': {
    path: 'helpnest-everything-bundle',
    name: 'Helpnest — Everything Bundle',
    tagline: 'Web Platform + Flutter Mobile App — all in one.',
    price: 89,
    originalPrice: 108,
    badge: 'Mobile App Included',
    features: [
      'Helpnest Web Platform',
      'Admin Panel & Analytics',
      'AI Chatbot (OpenAI + Claude)',
      'Support Ticketing System',
      'Knowledge Base Builder',
      'Visitor Tracking',
      'Embeddable Chat Widget',
      'Stripe + PayPal Billing',
      'Flutter Mobile App (Coming Soon)',
      'Lifetime License + Updates',
      '6 Months Support',
    ],
    addons: [
      {
        path: 'helpnest-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'helpnest-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We configure your VPS, PostgreSQL with vector extension, OCR, and deploy Helpnest — ready to go.',
        price: 149,
        originalPrice: 299,
        includes: [
          'VPS server setup & configuration',
          'PostgreSQL 14+ with pgvector extension',
          'OCR configuration',
          'AI provider (OpenAI / Claude) connection',
          'Stripe / PayPal payment configuration',
        ],
        excludes: [
          'Domain, hosting, VPS or server cost',
        ],
      },
    ],
  },

  'helpnest-exclusive-pack': {
    path: 'helpnest-exclusive-pack',
    name: 'Helpnest — Exclusive License',
    tagline: 'Full source code ownership. Build and sell your own SaaS.',
    price: 199,
    originalPrice: 299,
    badge: 'For Businesses',
    features: [
      'Everything in Everything Bundle',
      'Flutter Mobile App (Coming Soon)',
      'Build & Sell as a SaaS Business',
      'Unlimited Client Workspaces',
      'White-label — Remove All Branding',
      'Source Code Modification Rights',
      'Priority Support — 12 Months',
      'Lifetime License + Free Updates',
      'Cannot be resold or redistributed as-is',
    ],
    addons: [
      {
        path: 'helpnest-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'helpnest-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We configure your VPS, PostgreSQL with vector extension, OCR, and deploy Helpnest — ready to go.',
        price: 149,
        originalPrice: 299,
        includes: [
          'VPS server setup & configuration',
          'PostgreSQL 14+ with pgvector extension',
          'OCR configuration',
          'AI provider (OpenAI / Claude) connection',
          'Stripe / PayPal payment configuration',
        ],
        excludes: [
          'Domain, hosting, VPS or server cost',
        ],
      },
    ],
  },

  'prohandy-everything-bundle': {
    path: 'prohandy-everything-bundle',
    name: 'Prohandy — Everything Bundle',
    tagline: 'Web Platform + Client App + Provider App + WhatsApp Plugin',
    price: 69,
    originalPrice: 166,
    badge: 'Mobile Apps + WhatsApp',
    features: [
      'Prohandy Web Platform',
      'Laravel Admin Panel',
      'Cart-Based Service Booking',
      'Job Posting and Hiring Flow',
      'Real-Time Live Chat',
      'Google Maps Integration',
      '19 Payment Gateways',
      'Client Flutter Mobile App',
      'Provider Flutter Mobile App',
      'WhatsApp Order Plugin',
      'Lifetime License + Free Updates',
      '6 Months Support',
    ],
    addons: [
      {
        path: 'prohandy-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'prohandy-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We deploy Prohandy on your server, configure payment gateways, Google Maps, and hand you the keys.',
        price: 99,
        originalPrice: 299,
        includes: [
          'Server setup & configuration',
          'Google Maps API integration',
          'Payment gateway configuration',
          'Branding assets & color customization',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
      {
        path: 'prohandy-install-web-mobile',
        label: 'Full Done-For-You Launch (Web + Both Apps + WhatsApp)',
        description: 'Your complete home service marketplace, live in days. Web + client app + provider app + WhatsApp plugin — fully configured, branded, and ready to launch.',
        price: 499,
        originalPrice: 1090,
        bestValue: true,
        disables: ['prohandy-install-web'],
        includes: [
          'Server setup & configuration',
          'Google Maps API integration',
          'Payment gateway configuration',
          'Branding assets & color customization',
          'Client Flutter app build & configuration',
          'Provider Flutter app build & configuration',
          'WhatsApp Business API setup',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
          'Google Play / App Store developer accounts',
        ],
      },
      {
        path: 'prohandy-appstore-google',
        label: 'Publish Both Apps to Google Play — We Handle It',
        description: 'Both apps live on Google Play. We sign, submit, and follow up with Google until both are approved.',
        price: 398,
        originalPrice: 800,
        includes: [
          'APK signing & release build for both apps',
          'Google Play Console submission',
          'Store listing setup (title, description, screenshots)',
          'App review follow-up until approved',
        ],
        excludes: [
          'Google Play developer account ($25 one-time fee — you must own it)',
          'App icons or screenshots (you provide)',
        ],
      },
      {
        path: 'prohandy-appstore-apple',
        label: 'Publish Both Apps to App Store — We Handle It',
        description: 'Both apps live on the App Store. We handle signing, submission, and App Store review until approved.',
        price: 398,
        originalPrice: 800,
        includes: [
          'IPA build & code signing for both apps',
          'App Store Connect submission',
          'Store listing setup (title, description, screenshots)',
          'App review follow-up until approved',
        ],
        excludes: [
          'Apple Developer account ($99/yr — you must own it)',
          'App icons or screenshots (you provide)',
        ],
      },
    ],
  },

  'prohandy-exclusive-pack': {
    path: 'prohandy-exclusive-pack',
    name: 'Prohandy — Exclusive License',
    tagline: 'Full source code ownership. Build SaaS. Unlimited marketplaces.',
    price: 149,
    originalPrice: 299,
    badge: 'For Businesses',
    features: [
      'Everything in Everything Bundle',
      'Build & Sell as a SaaS Business',
      'Unlimited Service Marketplaces',
      'White-label — Remove All Branding',
      'Source Code Modification Rights',
      'Priority Support — 12 Months',
      'Lifetime License + Free Updates',
      'Cannot be resold or redistributed as-is',
    ],
    addons: [
      {
        path: 'prohandy-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We deploy Prohandy on your server, configure payment gateways, Google Maps, and hand you the keys.',
        price: 99,
        originalPrice: 299,
        includes: [
          'Server setup & configuration',
          'Google Maps API integration',
          'Payment gateway configuration',
          'Branding assets & color customization',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
      {
        path: 'prohandy-install-web-mobile',
        label: 'Full Done-For-You Launch (Web + Both Apps + WhatsApp)',
        description: 'Your complete home service marketplace, live in days. Web + client app + provider app + WhatsApp plugin — fully configured, branded, and ready to launch.',
        price: 499,
        originalPrice: 1090,
        bestValue: true,
        disables: ['prohandy-install-web'],
        includes: [
          'Server setup & configuration',
          'Google Maps API integration',
          'Payment gateway configuration',
          'Branding assets & color customization',
          'Client Flutter app build & configuration',
          'Provider Flutter app build & configuration',
          'WhatsApp Business API setup',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
          'Google Play / App Store developer accounts',
        ],
      },
    ],
  },

  'nazmart-exclusive-pack': {
    path: 'nazmart-exclusive-pack',
    name: 'Nazmart — Exclusive License',
    tagline: 'Web Platform + All Plugins + Mobile App + Domain Reseller',
    price: 299,
    originalPrice: 499,
    badge: 'Web + App + Plugins + Domain Reseller',
    features: [
      'Everything in Everything Bundle',
      'Domain Reseller Module',
      'Priority Support Included',
      'Lifetime License + Free Updates',
    ],
    addons: [
      {
        path: 'nazmart-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'nazmart-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We deploy Nazmart on your server, configure everything, and hand you the keys.',
        price: 149,
        originalPrice: 299,
        includes: [
          'Application installation & configuration on your server',
          'Branding assets & color customization',
          'Payment gateway configuration',
          'Translation / multi-language setup',
        ],
        excludes: [
          'Domain, hosting, VPS or server procurement',
        ],
      },
      {
        path: 'nazmart-install-web-and-mobile',
        label: 'Full Done-For-You Launch (Web + Mobile)',
        description: 'Your complete marketplace, live in days. Web platform + primary mobile app — fully configured, nothing left for you to figure out.',
        price: 449,
        originalPrice: 900,
        bestValue: true,
        disables: ['nazmart-install-web'],
        includes: [
          'Application installation & configuration on your server',
          'Branding assets & color customization',
          'Payment gateway configuration',
          'Translation / multi-language setup',
          'Mobile app build & configuration (1 primary master app)',
        ],
        excludes: [
          'Domain, hosting, VPS or server procurement',
          'Individual tenant app compilation or publishing',
        ],
      },
    ],
  },

  'gocar-everything-bundle': {
    path: 'gocar-everything-bundle',
    name: 'GoCar — Everything Bundle',
    tagline: 'Web Platform + Customer Flutter App — all in one.',
    price: 69,
    originalPrice: 88,
    badge: 'Mobile App Included',
    features: [
      'GoCar Web Platform',
      'Laravel Admin Panel',
      'Vehicle-Specific Service Booking',
      'Real-Time Order Tracking',
      'Branch Location Management',
      '19+ Payment Gateways',
      'Push and Email Notifications',
      'Coupon and Discount System',
      'Customer Flutter Mobile App (Android)',
      'Lifetime License + Free Updates',
      '6 Months Support',
    ],
    addons: [
      {
        path: 'gocar-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'gocar-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We deploy GoCar on your server, configure payment gateways, Google Maps, and hand you the keys.',
        price: 99,
        originalPrice: 299,
        includes: [
          'Server setup & configuration',
          'Google Maps API integration',
          'Payment gateway configuration',
          'Branding assets & color customization',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
      {
        path: 'gocar-install-web-mobile',
        label: 'Full Done-For-You Launch (Web + Mobile App)',
        description: 'Your complete car service marketplace, live in days. Web platform + branded customer app — fully configured, nothing left to figure out.',
        price: 349,
        originalPrice: 790,
        bestValue: true,
        disables: ['gocar-install-web'],
        includes: [
          'Server setup & configuration',
          'Google Maps API integration',
          'Payment gateway configuration',
          'Branding assets & color customization',
          'Customer Flutter app build & configuration',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
          'Google Play developer account (you must own it)',
        ],
      },
      {
        path: 'gocar-appstore-google',
        label: 'Publish Customer App to Google Play — We Handle It',
        description: 'Your app, live on Google Play. We sign, submit, and follow up with Google until approved.',
        price: 199,
        originalPrice: 399,
        includes: [
          'APK signing & release build',
          'Google Play Console submission',
          'Store listing setup (title, description, screenshots)',
          'App review follow-up until approved',
        ],
        excludes: [
          'Google Play developer account ($25 one-time fee — you must own it)',
          'App icons or screenshots (you provide)',
        ],
      },
      {
        path: 'gocar-appstore-apple',
        label: 'Publish Customer App to App Store — We Handle It',
        description: 'Your app, live on the App Store. We handle signing, submission, and App Store review until approved.',
        price: 199,
        originalPrice: 399,
        includes: [
          'IPA build & code signing',
          'App Store Connect submission',
          'Store listing setup (title, description, screenshots)',
          'App review follow-up until approved',
        ],
        excludes: [
          'Apple Developer account ($99/yr — you must own it)',
          'App icons or screenshots (you provide)',
        ],
      },
    ],
  },

  'gocar-exclusive-pack': {
    path: 'gocar-exclusive-pack',
    name: 'GoCar — Exclusive License',
    tagline: 'Full SaaS rights — build and sell unlimited car service marketplaces.',
    price: 149,
    originalPrice: 149,
    badge: 'SaaS Rights',
    features: [
      'Everything in Everything Bundle',
      'Build & Sell as a SaaS Business',
      'Unlimited Car Service Marketplaces',
      'White-label — Remove All Branding',
      'Source Code Modification Rights',
      'Priority Support — 12 Months',
      'Lifetime License + Free Updates',
    ],
    addons: [
      {
        path: 'gocar-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'gocar-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We deploy GoCar on your server, configure payment gateways, Google Maps, and hand you the keys.',
        price: 99,
        originalPrice: 299,
        includes: [
          'Server setup & configuration',
          'Google Maps API integration',
          'Payment gateway configuration',
          'Branding assets & color customization',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
      {
        path: 'gocar-install-web-mobile',
        label: 'Full Done-For-You Launch (Web + Mobile App)',
        description: 'Your complete car service marketplace, live in days. Web platform + branded customer app — fully configured, nothing left to figure out.',
        price: 349,
        originalPrice: 790,
        bestValue: true,
        disables: ['gocar-install-web'],
        includes: [
          'Server setup & configuration',
          'Google Maps API integration',
          'Payment gateway configuration',
          'Branding assets & color customization',
          'Customer Flutter app build & configuration',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
          'Google Play developer account (you must own it)',
        ],
      },
      {
        path: 'gocar-appstore-google',
        label: 'Publish Customer App to Google Play — We Handle It',
        description: 'Your app, live on Google Play. We sign, submit, and follow up with Google until approved.',
        price: 199,
        originalPrice: 399,
        includes: [
          'APK signing & release build',
          'Google Play Console submission',
          'Store listing setup (title, description, screenshots)',
          'App review follow-up until approved',
        ],
        excludes: [
          'Google Play developer account ($25 one-time fee — you must own it)',
          'App icons or screenshots (you provide)',
        ],
      },
      {
        path: 'gocar-appstore-apple',
        label: 'Publish Customer App to App Store — We Handle It',
        description: 'Your app, live on the App Store. We handle signing, submission, and App Store review until approved.',
        price: 199,
        originalPrice: 399,
        includes: [
          'IPA build & code signing',
          'App Store Connect submission',
          'Store listing setup (title, description, screenshots)',
          'App review follow-up until approved',
        ],
        excludes: [
          'Apple Developer account ($99/yr — you must own it)',
          'App icons or screenshots (you provide)',
        ],
      },
    ],
  },

  'qixer-everything-bundle': {
    path: 'qixer-everything-bundle',
    name: 'Qixer — Everything Bundle',
    tagline: 'Web Platform + 6 Add-ons + Buyer & Seller Flutter Apps',
    price: 99,
    originalPrice: 263,
    badge: 'Best Value',
    features: [
      'Qixer Web Frontend + Admin Panel',
      'Multi-Vendor Service Marketplace',
      'GPS Service Discovery',
      'Commission Revenue Model',
      '20+ Payment Gateways',
      'Buyer Wallet System',
      'Job Posting Module',
      'Seller Subscription Plans',
      'Live Chat Addon',
      'Buyer Flutter Mobile App (iOS & Android)',
      'Seller / Provider Flutter App (iOS & Android)',
      'Coupon & Discount System',
      'Review & Rating System',
      'Provider Availability & Booking Slots',
      'Service Area & Radius Control',
      'Role-Based Admin Permissions',
      'Multi-Language + RTL Support',
      'Lifetime License + Free Updates',
      '6 Months Support',
    ],
    addons: [
      {
        path: 'qixer-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'qixer-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We deploy Qixer on your server, configure payment gateways, and hand you the keys.',
        price: 99,
        originalPrice: 299,
        includes: [
          'Server setup & configuration',
          'Payment gateway configuration',
          'Branding assets & color customization',
          'Commission & subscription model configuration',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
        ],
      },
      {
        path: 'qixer-install-web-mobile',
        label: 'Full Done-For-You Launch (Web + Both Apps)',
        description: 'Your complete service marketplace, live in days. Web platform + buyer app + seller app — fully configured and branded.',
        price: 499,
        originalPrice: 1090,
        bestValue: true,
        disables: ['qixer-install-web'],
        includes: [
          'Server setup & configuration',
          'Payment gateway configuration',
          'Branding assets & color customization',
          'Commission & subscription model configuration',
          'Buyer Flutter app build & configuration',
          'Seller Flutter app build & configuration',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
          'Google Play / App Store developer accounts',
        ],
      },
      {
        path: 'qixer-appstore-google',
        label: 'Publish Both Apps to Google Play — We Handle It',
        description: 'Both apps live on Google Play. We sign, submit, and follow up with Google until both are approved.',
        price: 199,
        originalPrice: 399,
        includes: [
          'APK signing & release build for both apps',
          'Google Play Console submission',
          'Store listing setup (title, description, screenshots)',
          'App review follow-up until approved',
        ],
        excludes: [
          'Google Play developer account ($25 one-time fee — you must own it)',
          'App icons or screenshots (you provide)',
        ],
      },
      {
        path: 'qixer-appstore-apple',
        label: 'Publish Both Apps to App Store — We Handle It',
        description: 'Both apps live on the App Store. We handle signing, submission, and App Store review until approved.',
        price: 199,
        originalPrice: 399,
        includes: [
          'IPA build & code signing for both apps',
          'App Store Connect submission',
          'Store listing setup (title, description, screenshots)',
          'App review follow-up until approved',
        ],
        excludes: [
          'Apple Developer account ($99/yr — you must own it)',
          'App icons or screenshots (you provide)',
        ],
      },
    ],
  },

  'qixer-exclusive-pack': {
    path: 'qixer-exclusive-pack',
    name: 'Qixer — Exclusive License',
    tagline: 'SaaS Rights + White-label + Everything Bundle',
    price: 199,
    originalPrice: 463,
    badge: 'SaaS Rights',
    features: [
      'Everything in Everything Bundle',
      'Build & Sell as a SaaS Business',
      'Unlimited Service Marketplaces',
      'White-label — Remove All Branding',
      'Source Code Modification Rights',
      'Priority Support — 12 Months',
      'Lifetime License + Free Updates',
    ],
    addons: [
      {
        path: 'qixer-support-6m',
        label: 'Extend to 24 Months Support',
        description: 'Already have 12 months — extend to 24. Priority replies within 24h.',
        price: 99,
        originalPrice: 199,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '12 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'qixer-install-web-mobile',
        label: 'Full Done-For-You Launch (Web + Both Apps)',
        description: 'Your complete service marketplace, live in days. Web platform + buyer app + seller app — fully configured and branded.',
        price: 499,
        originalPrice: 1090,
        bestValue: true,
        includes: [
          'Server setup & configuration',
          'Payment gateway configuration',
          'Branding assets & color customization',
          'Commission & subscription model configuration',
          'Buyer Flutter app build & configuration',
          'Seller Flutter app build & configuration',
        ],
        excludes: [
          'Domain, hosting, VPS or server setup',
          'Google Play / App Store developer accounts',
        ],
      },
    ],
  },
  'botmerze-everyting-bundle': {
    path: 'botmerze-everyting-bundle',
    name: 'Botmerze — Everything Bundle',
    tagline: 'AI Chatbot SaaS + SaaS Rights — sell subscriptions to your clients.',
    price: 69,
    originalPrice: 149,
    badge: 'SaaS Rights Included',
    features: [
      'Complete Laravel 12 source code',
      'RAG-powered AI with pgvector',
      'WooCommerce & Shopify integration',
      'Knowledge base (PDF, URL, web pages)',
      'Lead generation & contact capture',
      'Multi-client SaaS management panel',
      'Drag-and-drop widget builder',
      '18+ payment gateways',
      'Built-in support ticket system',
      'Product recommendations & cross-sell',
      'SaaS rights — sell chatbot subscriptions',
      'Lifetime updates',
      '6 Months Support',
    ],
    addons: [
      {
        path: 'botmerze-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'botmerze-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We configure your VPS, PostgreSQL with pgvector, Tesseract OCR, and deploy Botmerze — ready to go.',
        price: 149,
        originalPrice: 299,
        includes: [
          'VPS server setup & configuration',
          'PostgreSQL 16+ with pgvector extension',
          'Tesseract OCR configuration',
          'OpenAI API connection',
          '18+ payment gateway configuration',
        ],
        excludes: [
          'Domain, hosting, VPS or server cost',
          'OpenAI API key',
        ],
      },
    ],
  },

  'botmerze-exclusive-pack': {
    path: 'botmerze-exclusive-pack',
    name: 'Botmerze — Exclusive License',
    tagline: 'Full source code ownership. White-label. Build and sell your own AI chatbot SaaS.',
    price: 199,
    originalPrice: 299,
    badge: 'For SaaS Businesses',
    features: [
      'Everything in Everything Bundle',
      'White-label — remove all Botmerze branding',
      'Multiple production deployments',
      'Source code modification rights',
      'Priority support — 12 months',
      'Sell chatbot access to unlimited clients',
      'Recurring revenue from day one',
      'Lifetime updates',
      'Cannot be resold or redistributed as-is',
    ],
    addons: [
      {
        path: 'botmerze-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already included in Exclusive — this extends an additional 12 months beyond that.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '12 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'botmerze-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup headache. We configure your VPS, PostgreSQL with pgvector, Tesseract OCR, and deploy Botmerze — ready to go.',
        price: 149,
        originalPrice: 299,
        includes: [
          'VPS server setup & configuration',
          'PostgreSQL 16+ with pgvector extension',
          'Tesseract OCR configuration',
          'OpenAI API connection',
          '18+ payment gateway configuration',
        ],
        excludes: [
          'Domain, hosting, VPS or server cost',
          'OpenAI API key',
        ],
      },
    ],
  },

  'multisaas-bundle-pack': {
    path: 'multisaas-bundle-pack',
    name: 'MultiSaas — Bundle Pack',
    tagline: 'Multi-tenant website builder SaaS + 5 premium plugins. Launch your platform.',
    price: 99,
    originalPrice: 199,
    badge: 'Best Value',
    features: [
      'MultiSaas Web Panel',
      'Cloud Storage Plugin',
      'Site Analytics Plugin',
      'Domain Reseller Plugin',
      'Restaurant Plugin',
      'Hotel Plugin',
      'Custom domain per tenant',
      '19+ payment gateways',
      '15+ multipurpose themes',
      '10+ business modules',
      '200+ languages supported',
      'Lifetime license validity',
      'Lifetime free updates',
      '6 months support',
      'Personal & commercial use',
      'Installation support',
    ],
    addons: [
      {
        path: 'multisaas-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'multisaas-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup. We configure your VPS with CloudPanel, install MultiSaas + all plugins, and connect your payment gateways. Ready in 48 hours.',
        price: 149,
        originalPrice: 299,
        includes: [
          'VPS server setup with CloudPanel',
          'MultiSaas web panel install',
          '5 plugins installed and configured',
          '2 themes installed',
          'Payment gateway configuration',
          'Domain & SSL setup',
        ],
        excludes: [
          'Domain, hosting, or VPS cost',
          'Payment gateway account fees',
        ],
      },
    ],
  },
  'greenmart-bundle-pack': {
    path: 'greenmart-bundle-pack',
    name: 'Grenmart — Everything Bundle',
    tagline: 'Grenmart web store + the Grenmart Flutter mobile app (Android & iOS).',
    price: 49,
    originalPrice: 89,
    badge: 'Best Value',
    features: [
      'Full Laravel source code',
      'Grenmart Flutter app (Android & iOS)',
      'Drag & drop page builder (50+ widgets)',
      '3 home page variants + shop layouts',
      '20+ payment gateways',
      'Advanced inventory, shipping & tax',
      'Coupons, campaigns & autocomplete search',
      'SEO tools + sitemap generation',
      'Default language (admin-set) + RTL support',
      'Lifetime license validity',
      'Lifetime free updates',
      '6 months support',
      'Personal & commercial use',
    ],
    addons: [
      {
        path: 'greenmart-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'greenmart-install-web',
        label: 'We Install the Web Store For You',
        description: 'Skip the setup. We deploy the Grenmart web store on your server, configure payment gateways, and hand you a working store. Ready in 48 hours.',
        price: 99,
        originalPrice: 199,
        includes: [
          'Server setup & web deployment',
          'Database & environment configuration',
          'Payment gateway configuration',
          'Domain & SSL setup',
          'Demo data import',
        ],
        excludes: [
          'Domain, hosting, or VPS cost',
          'Payment gateway account fees',
        ],
      },
      {
        path: 'greenmart-install-web-mobile',
        label: 'Done-For-You: Build & Release Web + Mobile',
        description: 'The complete launch package. We deploy your Grenmart web store and build, configure, and release your Flutter app to Google Play and the App Store — branded and connected to your store over API.',
        price: 399,
        originalPrice: 699,
        bestValue: true,
        disables: ['greenmart-install-web'],
        includes: [
          'Server setup & web deployment',
          'Payment gateway configuration',
          'Domain & SSL setup',
          'Flutter app build (Android & iOS) + branding',
          'App store submission & release (Google Play + App Store)',
          'Demo data import',
        ],
        excludes: [
          'Domain, hosting, or VPS cost',
          'Google Play / App Store developer accounts',
          'Payment gateway account fees',
        ],
      },
    ],
  },
  'greenmart-exclusive-pack': {
    path: 'greenmart-exclusive-pack',
    name: 'Grenmart — Exclusive License',
    tagline: 'Full source rights, branding removal, mobile app, and priority support.',
    price: 199,
    originalPrice: 399,
    badge: 'Exclusive',
    features: [
      'Everything in the Everything Bundle',
      'Grenmart Flutter app (Android & iOS)',
      'Full source code modification rights',
      'Remove / replace all branding',
      'Unlimited commercial projects',
      'Priority support — 12 months',
      'Lifetime license + free updates',
    ],
    addons: [
      {
        path: 'greenmart-support-6m',
        label: 'Extend Priority Support to 18 Months',
        description: 'Add 6 more months of priority support on top of the 12 included.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'greenmart-install-web',
        label: 'We Install the Web Store For You',
        description: 'Skip the setup. We deploy the Grenmart web store on your server, configure payment gateways, and hand you a working store. Ready in 48 hours.',
        price: 99,
        originalPrice: 199,
        includes: [
          'Server setup & web deployment',
          'Database & environment configuration',
          'Payment gateway configuration',
          'Domain & SSL setup',
          'Demo data import',
        ],
        excludes: [
          'Domain, hosting, or VPS cost',
          'Payment gateway account fees',
        ],
      },
      {
        path: 'greenmart-install-web-mobile',
        label: 'Done-For-You: Build & Release Web + Mobile',
        description: 'The complete launch package. We deploy your Grenmart web store and build, configure, and release your Flutter app to Google Play and the App Store — branded and connected to your store over API.',
        price: 399,
        originalPrice: 699,
        bestValue: true,
        disables: ['greenmart-install-web'],
        includes: [
          'Server setup & web deployment',
          'Payment gateway configuration',
          'Domain & SSL setup',
          'Flutter app build (Android & iOS) + branding',
          'App store submission & release (Google Play + App Store)',
          'Demo data import',
        ],
        excludes: [
          'Domain, hosting, or VPS cost',
          'Google Play / App Store developer accounts',
          'Payment gateway account fees',
        ],
      },
    ],
  },
  'multisaas-exclusive-pack': {
    path: 'multisaas-exclusive-pack',
    name: 'MultiSaas — Exclusive Bundle Pack',
    tagline: 'Everything in the Bundle Pack plus full source rights and priority support.',
    price: 299,
    originalPrice: 499,
    badge: 'Exclusive',
    features: [
      'Everything in Bundle Pack',
      'All 5 Premium Plugins',
      'Full Source Code Modification Rights',
      'Remove / Replace All Branding',
      'No License Key Enforcement',
      'Priority Support — 12 Months',
      'Commercial Use — Unlimited Projects',
      'Lifetime License + Free Updates',
    ],
    addons: [
      {
        path: 'multisaas-support-6m',
        label: 'Extend to 12 Months Support',
        description: 'Already have 6 months free — double it to 12. Priority replies within 24h.',
        price: 49,
        originalPrice: 99,
        sidebarUpsell: true,
        includes: [
          'Priority ticket support',
          '6 additional months from purchase date',
          'Bug fixes and compatibility help',
        ],
      },
      {
        path: 'multisaas-install-web',
        label: 'We Install & Launch It For You',
        description: 'Skip the setup. We configure your VPS with CloudPanel, install MultiSaas + all plugins, and connect your payment gateways. Ready in 48 hours.',
        price: 149,
        originalPrice: 299,
        includes: [
          'VPS server setup with CloudPanel',
          'MultiSaas web panel install',
          '5 plugins installed and configured',
          '2 themes installed',
          'Payment gateway configuration',
          'Domain & SSL setup',
        ],
        excludes: [
          'Domain, hosting, or VPS cost',
          'Payment gateway account fees',
        ],
      },
    ],
  },

};

export function getCheckoutProduct(path: string | undefined | null): CheckoutProduct | null {
  if (!path) return null;
  return PRODUCTS[path] ?? null;
}
