// Auto-fetched from each provider's own website favicon. Providers without a
// reliably matched official domain fall back to a text-only pill (no entry here).
export const PROVIDER_LOGOS: Record<string, string> = {
  '2Checkout': '/logos/2checkout.png',
  'Adyen': '/logos/adyen.png',
  'Africa\'s Talking': '/logos/africa-s-talking.png',
  'Amazon SNS': '/logos/amazon-sns.png',
  'Aramex': '/logos/aramex.png',
  'Authorize.Net': '/logos/authorize-net.png',
  'BDCourier': '/logos/bdcourier.png',
  'Blue Dart': '/logos/blue-dart.png',
  'Bob Go': '/logos/bob-go.png',
  'BulkSMSBD': '/logos/bulksmsbd.png',
  'Bureau': '/logos/bureau.png',
  'Cashfree': '/logos/cashfree.png',
  'Cequens': '/logos/cequens.png',
  'Clickatell': '/logos/clickatell.png',
  'Correios': '/logos/correios.png',
  'DHL Express': '/logos/dhl-express.png',
  'Delhivery': '/logos/delhivery.png',
  'EasyPost': '/logos/easypost.png',
  'Fast2SMS': '/logos/fast2sms.png',
  'Fawry': '/logos/fawry.png',
  'FedEx': '/logos/fedex.png',
  'Flutterwave': '/logos/flutterwave.png',
  'FraudBD': '/logos/fraudbd.png',
  'GIG Logistics': '/logos/gig-logistics.png',
  'Gupshup': '/logos/gupshup.png',
  'IPQualityScore': '/logos/ipqualityscore.png',
  'Infobip': '/logos/infobip.png',
  'JazzCash': '/logos/jazzcash.png',
  'KakaoPay': '/logos/kakaopay.png',
  'Kwik Delivery': '/logos/kwik-delivery.png',
  'Loggi': '/logos/loggi.png',
  'MRAM': '/logos/mram.png',
  'MSG91': '/logos/msg91.png',
  'MTN MoMo': '/logos/mtn-momo.png',
  'MaxMind minFraud': '/logos/maxmind-minfraud.png',
  'Melhor Envio': '/logos/melhor-envio.png',
  'MercadoPago': '/logos/mercadopago.png',
  'MessageBird': '/logos/messagebird.png',
  'Midtrans': '/logos/midtrans.png',
  'Mollie': '/logos/mollie.png',
  'Monnify': '/logos/monnify.png',
  'Moyasar': '/logos/moyasar.png',
  'Nagad': '/logos/nagad.png',
  'Naqel Express': '/logos/naqel-express.png',
  'Paddle': '/logos/paddle.png',
  'Pagar.me': '/logos/pagar-me.png',
  'Pathao': '/logos/pathao.png',
  'PayPal': '/logos/paypal.png',
  'PayTabs': '/logos/paytabs.png',
  'PayU India': '/logos/payu-india.png',
  'Paystack': '/logos/paystack.png',
  'Paytm': '/logos/paytm.png',
  'Peach Payments': '/logos/peach-payments.png',
  'PhonePe': '/logos/phonepe.png',
  'Plivo': '/logos/plivo.png',
  'Ravelin': '/logos/ravelin.png',
  'Razorpay': '/logos/razorpay.png',
  'RedX': '/logos/redx.png',
  'SEON': '/logos/seon.png',
  'SMS.BD': '/logos/sms-bd.png',
  'SMSA Express': '/logos/smsa-express.png',
  'SSLCOMMERZ': '/logos/sslcommerz.png',
  'Sendbox': '/logos/sendbox.png',
  'Shippo': '/logos/shippo.png',
  'Shiprocket': '/logos/shiprocket.png',
  'ShurjoPay': '/logos/shurjopay.png',
  'Sift': '/logos/sift.png',
  'Sinch': '/logos/sinch.png',
  'Smile ID': '/logos/smile-id.png',
  'Square': '/logos/square.png',
  'Steadfast': '/logos/steadfast.png',
  'Stripe': '/logos/stripe.png',
  'Taqnyat': '/logos/taqnyat.png',
  'Telnyx': '/logos/telnyx.png',
  'Termii': '/logos/termii.png',
  'Torod': '/logos/torod.png',
  'Twilio': '/logos/twilio.png',
  'UPS': '/logos/ups.png',
  'Unifonic': '/logos/unifonic.png',
  'Uqudo': '/logos/uqudo.png',
  'Vipps MobilePay': '/logos/vipps-mobilepay.png',
  'Vonage': '/logos/vonage.png',
  'Xendit': '/logos/xendit.png',
  'Yoco': '/logos/yoco.png',
  'Youverify': '/logos/youverify.png',
  'aamarPay': '/logos/aamarpay.png',
  'iyzico': '/logos/iyzico.png',
};
